name: 'EpicBot'
description: 'Manage Epic issues, and associated workload issues'
inputs:
  secret-token:
    description: 'Secret token giving access to the repo'
    required: true
  epic-prefix:
    description: 'Issue title prefix indicating it is an Epic'
    required: true
    default: 'Epic /'
  workoad-marker:
    description: 'Identifying text (within a heading) denoting start of workload issue section'
    required: false
    default: 'Workload'
  close-completed-epics:
    description: 'Whether to automatically close Epics when all workload tasks are complete'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'index.js'
