name: 'EpicBot'
description: 'Manage Epic issues, and associated workload issues'
inputs:
  secret-token:
    description: 'Secret token giving access to the repo'
    required: true
  epic-prefix:
    description: 'Issue title prefix indicating it is an Epic'
    required: true
    default: 'Epic /'
  skip-section:
    description: 'Identifying text starting a heading denoting a non-task section'
    required: false
    default: 'Notes'
  close-completed-epics:
    description: 'Whether to automatically close Epics when all workload tasks are complete'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'index.js'
