name: EpicBot

on:
  issues:
    types: [opened, edited]

jobs:
  manage_epics:
    runs-on: ubuntu-latest
    name: Manage Epics
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Manage Epics
        uses: ./ # Uses an action in the root directory
        with:
          action-token: "${{ secrets.MAIN_SECRET }}"

